name: Build and Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Linux x64
          - os: ubuntu-latest
            target: linux-x64
            build_target: bun-linux-x64

          # Linux ARM64
          - os: ubuntu-latest
            target: linux-arm64
            build_target: bun-linux-arm64

          # macOS x64
          - os: macos-latest
            target: darwin-x64
            build_target: bun-darwin-x64

          # macOS ARM64 (Apple Silicon)
          - os: macos-latest
            target: darwin-arm64
            build_target: bun-darwin-arm64

          # Windows x64
          - os: windows-latest
            target: windows-x64
            build_target: bun-windows-x64

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build executable
        run: |
          bun build ./index.ts --compile --target=${{ matrix.build_target }} --outfile ./bin/fcrawl-${{ matrix.target }}
        shell: bash

      - name: Add .exe extension for Windows
        if: matrix.os == 'windows-latest'
        run: |
          mv ./bin/fcrawl-${{ matrix.target }} ./bin/fcrawl-${{ matrix.target }}.exe
        shell: bash

      - name: Create archive
        run: |
          cd bin
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            7z a ../fcrawl-${{ matrix.target }}.zip fcrawl-${{ matrix.target }}.exe
          else
            tar -czf ../fcrawl-${{ matrix.target }}.tar.gz fcrawl-${{ matrix.target }}
          fi
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fcrawl-${{ matrix.target }}
          path: fcrawl-${{ matrix.target }}.*

  github-release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            fcrawl-linux-x64/fcrawl-linux-x64.tar.gz
            fcrawl-linux-arm64/fcrawl-linux-arm64.tar.gz
            fcrawl-darwin-x64/fcrawl-darwin-x64.tar.gz
            fcrawl-darwin-arm64/fcrawl-darwin-arm64.tar.gz
            fcrawl-windows-x64/fcrawl-windows-x64.zip